create table member
(
    id bigint generated by default as identity,
    m_id varchar(30),
    pw varchar(30),
    email varchar(40),
    qna varchar(20),
    name varchar(255),
    primary key(id),
    unique (m_id),
    unique (email)
);